export default {
    cookieBanner: '[data-component="cookieBanner"]',
    button: '[data-component="button"]',
    /* button_interestCalculator: `${button}[data-mod="interestCalculator"]`,
    button_mortgageRequest: `${button}[data-mod="mortgageRequest"]`,
    button_getToKnowMe: `${button}[data-mod="getToKnowMe"]`, */
    interestCalculatorButton:
        '[data-component="button"][data-mod="interestCalculator"]',
    mortgageRequestButton:
        '[data-component="button"][data-mod="mortgageRequest"]',
    getToKnowMeButton: '[data-component="button"][data-mod="getToKnowMe"]',
    topHeader: '[data-component="topHeader"]',
    headerMobile: '[data-component="headerMobile"]',
    link: '[data-component="link"]',
    // linkBanner: `${link}[data-mod="banner"]`,
    image: '[data-component="image"]',
    logoArea: '[data-component="logoArea"]',
    textArea: '[data-component="textArea"]',
    burgerMenu: '[data-component="burgerMenu"]',
    offcanvas: '[data-component="offcanvas"]',
    navigation: '[data-component="navigation"]',
    navigationItem: '[data-component="navigationItem"]',
    inputField: '[data-component="inputField"]',
    selectField: '[data-component="selectField"]',
    checkbox: '[data-component="checkbox"]',
    home: '[data-component="home"]',
    aboutMe: '[data-component="aboutMe"]',
    consultation: '[data-component="consultation"]',
    service: '[data-component="service"]',
    contact: '[data-component="contact"]',
    impress: '[data-component="impress"]',
    privacyPolicy: '[data-component="privacyPolicy"]',
    contentCard: '[data-component="contentCard"]',
    contentRow: '[data-component="contentRow"]',
    cardTextArea: '[data-component="cardTextArea"]',
    headline: '[data-component="headline"]',
    subHeadline: '[data-component="subHeadline"]',
    introHints: '[data-component="introHints"]',
    benefitList: '[data-component="benefitList"]',
    bottomFooter: '[data-component="bottomFooter"]',
    headline_h1: `${headline}[data-mod="h1"]`,
    headline_h2: `${headline}[data-mod="h2"]`,
    h1: '[data-mod="h1"]',
    h2: '[data-mod="h2"]',
    banner: '[data-component="link"][data-mod="banner"]',
    interestCalculator: '[data-mod="interestCalculator"]',
    mortgageRequest: '[data-mod="mortgageRequest"]',
    getToKnowMe: '[data-mod="getToKnowMe"]',
    intro: '[data-mod="intro"]',
    benefits: '[data-mod="benefits"]',
    contactOptions: '[data-mod="contactOptions"]',
    organization: '[data-mod="organization"]',
    salutation: '[data-mod="salutation"]',
    name: '[data-mod="name"]',
    email: '[data-mod="email"]',
    hpot1: '[data-mod="hpot1"]',
    send: '[data-mod="send"]',
    contactOptions: '[data-mod="contactOptions"]',
};
